### PR TITLE
Fix all contacts showing when no match; create chips with space

### PR DESCRIPTION
**Pull request by jungyang**
Two improvements for email:
1. Fix the issue where all contacts are showing when you enter two characters and there is no match
2. Allow using spaces to create chips (using @tyczj's solution in https://github.com/klinker41/android-chips/issues/5)

### CODE REVIEW

**Comment by klinker41** [comment]
For the first point, I did this on purpose. It was an easy workaround in my app for showing a list of everyone.

**Comment by jungyang** [comment]
For showing all contacts, the showAllContacts method would still work.

**Comment by klinker41** [comment]
Maybe I'm misremembering, I'll have to take a look at it when I can.

**Comment by klinker41** [comment]
I remember why I had to mess with this a little bit and end up with a hacky solution, I wanted to be able to have a multiselect on it so that the list didn't hide after clicking on a name. I believe that is why its in the state you found it in.

**Comment by jungyang** [comment]
The functionality you wanted is still there. If you run your sample app (with my branch) and click the plus button, it will display all the contacts and the list won't hide after you click on a name. This is the same behavior as before.

The only thing I changed is if you type in two characters that doesn't match anything in the contacts, the list won't show. In your current code, the list would either pop up and then immediately disappear or pop up and stay on the screen (depends on the device) when you type in two characters that doesn't match anything.

**Comment by klinker41** [comment]
Sorry this took so long for me to get around to, merging now.

**Pull request merged**
